title: Documentation
doc_version: 1.2.0
url: https://guided-filter.nlamprian.me

permalink: /:categories/:title
markdown: kramdown
kramdown:
  input: GFM 
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jemoji
  - rouge
